GET http://localhost:3000/api/genero

###

GET http://localhost:3000/api/genero/4

###

POST http://localhost:3000/api/genero
Content-Type: application/json

{
  "nombre": "test original"
}

###

DELETE http://localhost:3000/api/genero/4

###

PUT http://localhost:3000/api/genero
Content-Type: application/json

{
  "id": 4,
  "nombre": "test updated"
}
